-- AlterTable
ALTER TABLE "jobs" ALTER COLUMN "applies" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sponsored" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "zip_codes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fip" SET DATA TYPE DOUBLE PRECISION;
